// This file contains all the relevant data for each planet. Using this, I only have to create one html file for every planet page
export const planetData = {
    mercury: {
        name: "Mercury",
        classification: "Terrestrial Planet",
        radius: { string: "2,439 km", value: 2439.7 },
        rotationSpeed: { string: "~58 Earth days", value: 648 },
        mass: "3.30 x 10^23 kg",
        gravity: "3.7 m/s²",
        distanceFromSun: {
            string: "57.9 million km",
            value: 57.9,
        },
        orbitalPeriod: {
            string: "88 Earth days",
            value: 88,
        },
        image: "../images/mercury.jpg",
        texture: "../images/mercury_texture.jpg",
        description:
            "Mercury is the smallest planet in our solar system and closest to the Sun. It has a rocky surface and experiences extreme temperatures.",
        numberOfMoons: "0",
        surfaceTemperature: "-173 to 427 °C",
        interestingFact:
            "Mercury has a very thin atmosphere, which means it cannot retain heat. This results in drastic temperature changes between day and night.",
    },
    venus: {
        name: "Venus",
        classification: "Terrestrial Planet",
        radius: { string: "6,052 km", value: 6051.8 },
        rotationSpeed: { string: "~243 Earth days", value: -5832 },
        mass: "4.87 x 10^24 kg",
        gravity: "8.87 m/s²",
        distanceFromSun: { string: "108.2 million km", value: 108.2 },
        orbitalPeriod: { string: "225 Earth days", value: 225 },
        image: "../images/venus.jpg",
        texture: "../images/venus_texture.jpg",
        description:
            "Venus is the second planet from the Sun and is often called Earth's sister planet due to its similar size. It has a thick atmosphere that traps heat, making it the hottest planet in our solar system.",
        numberOfMoons: "0",
        surfaceTemperature: "462 °C",
        interestingFact:
            "Venus is the hottest planet in our solar system, even though Mercury is closer to the Sun.",
    },
    earth: {
        name: "Earth",
        classification: "Terrestrial Planet",
        radius: { string: "6,378 km", value: 6378 },
        rotationSpeed: { string: "24 Earth hours", value: 24 },
        mass: "5.97 x 10^24 kg",
        gravity: "9.81 m/s²",
        distanceFromSun: { string: "149.6 million km", value: 155.6 },
        orbitalPeriod: { string: "365.25 Earth days", value: 365.25 },
        image: "../images/earth.jpg",
        texture: "../images/earth_texture.jpg",
        description:
            "Earth is the third planet from the Sun and the only known planet to support life. It has a diverse climate and a rich variety of ecosystems.",
        numberOfMoons: "1",
        surfaceTemperature: "15 °C",
        interestingFact: "Earth is the only planet known to support life.",
    },
    mars: {
        name: "Mars",
        classification: "Terrestrial Planet",
        radius: { string: "3390 km", value: 3389.5 },
        rotationSpeed: { string: "~24.6 Earth hours", value: 24.6 },
        mass: "6.42 x 10^23 kg",
        gravity: "3.71 m/s²",
        distanceFromSun: { string: "227.9 million km", value: 227.9 },
        orbitalPeriod: { string: "687 Earth days", value: 687 },
        image: "../images/mars.jpg",
        texture: "../images/mars_texture.jpg",
        description:
            "Mars is the fourth planet from the Sun and is often called the Red Planet due to its reddish appearance. It has a thin atmosphere and is home to the largest volcano in the solar system, Olympus Mons.",
        numberOfMoons: "2",
        surfaceTemperature: "-65 °C",
        interestingFact:
            "Mars has the largest volcano in the solar system, Olympus Mons.",
    },
    jupiter: {
        name: "Jupiter",
        classification: "Gas Giant",
        radius: { string: "69911 km", value: 69911 },
        rotationSpeed: { string: "~ 9.9 Earth hours", value: 9.9 },
        mass: "1.90 x 10^27 kg",
        gravity: "24.79 m/s²",
        distanceFromSun: { string: "778.5 million km", value: 778.5 },
        orbitalPeriod: { string: "4,333 Earth days", value: 4333 },
        image: "../images/jupiter.jpg",
        texture: "../images/jupiter_texture.jpg",
        description:
            "Jupiter is the largest planet in our solar system and is known for its Great Red Spot, a giant storm that has been raging for centuries. It has a strong magnetic field and dozens of moons.",
        numberOfMoons: "79",
        surfaceTemperature: "-110 °C",
        interestingFact: "Jupiter is the largest planet in our solar system.",
    },
    saturn: {
        name: "Saturn",
        classification: "Gas Giant",
        radius: { string: "58,232 km", value: 58232 },
        rotationSpeed: { string: "~10.7 Earth hours", value: 10.7 },
        mass: "5.68 x 10^26 kg",
        gravity: "10.44 m/s²",
        distanceFromSun: { string: "1.43 billion km", value: 1432 },
        orbitalPeriod: { string: "10,759 Earth days", value: 10759 },
        image: "../images/saturn.jpg",
        texture: "../images/saturn_texture.jpg",
        description:
            "Saturn is the second-largest planet in our solar system and is famous for its stunning ring system, which is made up of ice and rock particles. It has a low density and could float in water.",
        numberOfMoons: "82",
        surfaceTemperature: "-178 °C",
        interestingFact:
            "Saturn has the most extensive ring system in our solar system.",
    },
    uranus: {
        name: "Uranus",
        classification: "Ice Giant",
        radius: { string: "25,362 km", value: 25362 },
        rotationSpeed: { string: "~17 Earth hours", value: 17 },
        mass: "8.68 x 10^25 kg",
        gravity: "8.69 m/s²",
        distanceFromSun: { string: "2.87 billion km", value: 2871 },
        orbitalPeriod: { string: "30,688 Earth days", value: 30688 },
        image: "../images/uranus.jpg",
        texture: "../images/uranus_texture.jpg",
        description:
            "Uranus is the seventh planet from the Sun and is unique for its tilted axis, which causes it to rotate on its side. It has a blue-green color due to methane in its atmosphere.",
        numberOfMoons: "27",
        surfaceTemperature: "-195 °C",
        interestingFact:
            "Uranus rotates on its side, making it unique in our solar system.",
    },
    neptune: {
        name: "Neptune",
        classification: "Ice Giant",
        radius: { string: "24,622 km", value: 24622 },
        rotationSpeed: { string: "~16 Earth hours", value: 16 },
        mass: "1.02 x 10^26 kg",
        gravity: "11.15 m/s²",
        distanceFromSun: { string: "4.5 billion km", value: 4495 },
        orbitalPeriod: { string: "60,182 Earth days", value: 60182 },
        image: "../images/neptune.jpg",
        texture: "../images/neptune_texture.jpg",
        description:
            "Neptune is the eighth and farthest planet from the Sun. It has a deep blue color and is known for its strong winds, which can reach speeds of up to 2,100 km/h. It also has a faint ring system and several moons.",
        numberOfMoons: "14",
        surfaceTemperature: "-200 °C",
        interestingFact: "Neptune has the strongest winds in our solar system.",
    },
};
